/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.cmf.occi.core.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.cmf.occi.core.xtext.services.OCCIGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class OCCISyntacticSequencer extends AbstractSyntacticSequencer {

	protected OCCIGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Extension___AsKeyword_6_2_0_IDTerminalRuleCall_6_2_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (OCCIGrammarAccess) access;
		match_Extension___AsKeyword_6_2_0_IDTerminalRuleCall_6_2_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getExtensionAccess().getAsKeyword_6_2_0()), new TokenAlias(false, false, grammarAccess.getExtensionAccess().getIDTerminalRuleCall_6_2_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getIDRule())
			return getIDToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal ID  		: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	 */
	protected String getIDToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Extension___AsKeyword_6_2_0_IDTerminalRuleCall_6_2_1__q.equals(syntax))
				emit_Extension___AsKeyword_6_2_0_IDTerminalRuleCall_6_2_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('as' ID)?
	 *
	 * This ambiguous syntax occurs at:
	 *     import+=[Extension|STRING] (ambiguity) 'import' import+=[Extension|STRING]
	 *     import+=[Extension|STRING] (ambiguity) (rule end)
	 *     import+=[Extension|STRING] (ambiguity) kinds+=Kind
	 *     import+=[Extension|STRING] (ambiguity) mixins+=Mixin
	 *     import+=[Extension|STRING] (ambiguity) types+=DataType
	 */
	protected void emit_Extension___AsKeyword_6_2_0_IDTerminalRuleCall_6_2_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
