/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.cmf.occi.core.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOCCIScopeProvider extends DelegatingScopeProvider {
}
