/**
 * generated by Xtext 2.11.0
 */
package org.eclipse.cmf.occi.core.xtext.ide;

import org.eclipse.cmf.occi.core.xtext.ide.AbstractOCCIIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class OCCIIdeModule extends AbstractOCCIIdeModule {
}
