/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.cmf.occi.core.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.cmf.occi.core.xtext.parser.antlr.internal.InternalOCCIParser;
import org.eclipse.cmf.occi.core.xtext.services.OCCIGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class OCCIParser extends AbstractAntlrParser {

	@Inject
	private OCCIGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalOCCIParser createParser(XtextTokenStream stream) {
		return new InternalOCCIParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Grammar";
	}

	public OCCIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OCCIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
