/**
 * generated by Xtext 2.11.0
 */
package org.eclipse.cmf.occi.core.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.cmf.occi.core.AttributeState;
import org.eclipse.cmf.occi.core.Configuration;
import org.eclipse.cmf.occi.core.Link;
import org.eclipse.cmf.occi.core.Mixin;
import org.eclipse.cmf.occi.core.MixinBase;
import org.eclipse.cmf.occi.core.OCCIPackage;
import org.eclipse.cmf.occi.core.Resource;
import org.eclipse.cmf.occi.core.xtext.services.OCCIGrammarAccess;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;

@SuppressWarnings("all")
public class OCCIFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private OCCIGrammarAccess _oCCIGrammarAccess;
  
  protected void _format(final Configuration configuration, @Extension final IFormattableDocument document) {
    final ISemanticRegion klocation = this.textRegionExtensions.regionFor(configuration).feature(OCCIPackage.Literals.CONFIGURATION__LOCATION);
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.setNewLines(2);
    };
    document.append(klocation, _function);
    final ISemanticRegion kuse = this.textRegionExtensions.regionFor(configuration).keyword(")");
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.setNewLines(2);
    };
    document.append(kuse, _function_1);
    EList<Resource> _resources = configuration.getResources();
    for (final Resource resource : _resources) {
      document.<Resource>format(resource);
    }
    EList<Mixin> _mixins = configuration.getMixins();
    for (final Mixin mixin : _mixins) {
      document.<Mixin>format(mixin);
    }
  }
  
  protected void _format(final Resource resource, @Extension final IFormattableDocument document) {
    final ISemanticRegion kkind = this.textRegionExtensions.regionFor(resource).feature(OCCIPackage.Literals.ENTITY__TITLE);
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.setNewLines(1);
    };
    document.append(kkind, _function);
    final ISemanticRegion kattribute = this.textRegionExtensions.regionFor(resource).assignment(this._oCCIGrammarAccess.getResourceAccess().getAttributesAssignment_8());
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.setNewLines(2);
    };
    document.append(kattribute, _function_1);
    EList<MixinBase> _parts = resource.getParts();
    for (final MixinBase mixinBase : _parts) {
      document.<MixinBase>format(mixinBase);
    }
    EList<AttributeState> _attributes = resource.getAttributes();
    for (final AttributeState attributeState : _attributes) {
      document.<AttributeState>format(attributeState);
    }
    EList<Link> _links = resource.getLinks();
    for (final Link link : _links) {
      document.<Link>format(link);
    }
  }
  
  public void format(final Object resource, final IFormattableDocument document) {
    if (resource instanceof XtextResource) {
      _format((XtextResource)resource, document);
      return;
    } else if (resource instanceof Resource) {
      _format((Resource)resource, document);
      return;
    } else if (resource instanceof Configuration) {
      _format((Configuration)resource, document);
      return;
    } else if (resource instanceof EObject) {
      _format((EObject)resource, document);
      return;
    } else if (resource == null) {
      _format((Void)null, document);
      return;
    } else if (resource != null) {
      _format(resource, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(resource, document).toString());
    }
  }
}
