/*
 * generated by Xtext 2.11.0
 */
package org.eclipse.cmf.occi.core.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.cmf.occi.core.xtext.ide.contentassist.antlr.internal.InternalOCCIParser;
import org.eclipse.cmf.occi.core.xtext.services.OCCIGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class OCCIParser extends AbstractContentAssistParser {

	@Inject
	private OCCIGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalOCCIParser createParser() {
		InternalOCCIParser result = new InternalOCCIParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getExtensionAccess().getAlternatives_7(), "rule__Extension__Alternatives_7");
					put(grammarAccess.getKindAccess().getAlternatives_10(), "rule__Kind__Alternatives_10");
					put(grammarAccess.getMixinAccess().getAlternatives_9(), "rule__Mixin__Alternatives_9");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getQualifiedIDAccess().getAlternatives(), "rule__QualifiedID__Alternatives");
					put(grammarAccess.getNameIDAccess().getAlternatives(), "rule__NameID__Alternatives");
					put(grammarAccess.getNameIDAccess().getAlternatives_0_1(), "rule__NameID__Alternatives_0_1");
					put(grammarAccess.getKEYWORDAccess().getAlternatives(), "rule__KEYWORD__Alternatives");
					put(grammarAccess.getNumericTypeEnumAccess().getAlternatives(), "rule__NumericTypeEnum__Alternatives");
					put(grammarAccess.getExtensionAccess().getGroup(), "rule__Extension__Group__0");
					put(grammarAccess.getExtensionAccess().getGroup_4(), "rule__Extension__Group_4__0");
					put(grammarAccess.getExtensionAccess().getGroup_5(), "rule__Extension__Group_5__0");
					put(grammarAccess.getExtensionAccess().getGroup_6(), "rule__Extension__Group_6__0");
					put(grammarAccess.getExtensionAccess().getGroup_6_2(), "rule__Extension__Group_6_2__0");
					put(grammarAccess.getKindAccess().getGroup(), "rule__Kind__Group__0");
					put(grammarAccess.getKindAccess().getGroup_2(), "rule__Kind__Group_2__0");
					put(grammarAccess.getKindAccess().getGroup_3(), "rule__Kind__Group_3__0");
					put(grammarAccess.getKindAccess().getGroup_4(), "rule__Kind__Group_4__0");
					put(grammarAccess.getKindAccess().getGroup_5(), "rule__Kind__Group_5__0");
					put(grammarAccess.getKindAccess().getGroup_5_3(), "rule__Kind__Group_5_3__0");
					put(grammarAccess.getKindAccess().getGroup_7(), "rule__Kind__Group_7__0");
					put(grammarAccess.getKindAccess().getGroup_11(), "rule__Kind__Group_11__0");
					put(grammarAccess.getMixinAccess().getGroup(), "rule__Mixin__Group__0");
					put(grammarAccess.getMixinAccess().getGroup_2(), "rule__Mixin__Group_2__0");
					put(grammarAccess.getMixinAccess().getGroup_2_3(), "rule__Mixin__Group_2_3__0");
					put(grammarAccess.getMixinAccess().getGroup_3(), "rule__Mixin__Group_3__0");
					put(grammarAccess.getMixinAccess().getGroup_3_3(), "rule__Mixin__Group_3_3__0");
					put(grammarAccess.getMixinAccess().getGroup_4(), "rule__Mixin__Group_4__0");
					put(grammarAccess.getMixinAccess().getGroup_4_3(), "rule__Mixin__Group_4_3__0");
					put(grammarAccess.getMixinAccess().getGroup_8(), "rule__Mixin__Group_8__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_5(), "rule__Attribute__Group_5__0");
					put(grammarAccess.getAttributeAccess().getGroup_6(), "rule__Attribute__Group_6__0");
					put(grammarAccess.getAttributeAccess().getGroup_7(), "rule__Attribute__Group_7__0");
					put(grammarAccess.getAttributeAccess().getGroup_7_1(), "rule__Attribute__Group_7_1__0");
					put(grammarAccess.getAttributeAccess().getGroup_8(), "rule__Attribute__Group_8__0");
					put(grammarAccess.getAttributeAccess().getGroup_8_3(), "rule__Attribute__Group_8_3__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
					put(grammarAccess.getActionAccess().getGroup_4_2(), "rule__Action__Group_4_2__0");
					put(grammarAccess.getActionAccess().getGroup_5(), "rule__Action__Group_5__0");
					put(grammarAccess.getActionAccess().getGroup_6(), "rule__Action__Group_6__0");
					put(grammarAccess.getActionAccess().getGroup_6_3(), "rule__Action__Group_6_3__0");
					put(grammarAccess.getParameterDeclAccess().getGroup(), "rule__ParameterDecl__Group__0");
					put(grammarAccess.getParameterDeclAccess().getGroup_3(), "rule__ParameterDecl__Group_3__0");
					put(grammarAccess.getConstraintAccess().getGroup(), "rule__Constraint__Group__0");
					put(grammarAccess.getConstraintAccess().getGroup_2(), "rule__Constraint__Group_2__0");
					put(grammarAccess.getFSMAccess().getGroup(), "rule__FSM__Group__0");
					put(grammarAccess.getFSMAccess().getGroup_4(), "rule__FSM__Group_4__0");
					put(grammarAccess.getFSMAccess().getGroup_4_3(), "rule__FSM__Group_4_3__0");
					put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
					put(grammarAccess.getStateAccess().getGroup_4(), "rule__State__Group_4__0");
					put(grammarAccess.getStateAccess().getGroup_5(), "rule__State__Group_5__0");
					put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup_4(), "rule__Transition__Group_4__0");
					put(grammarAccess.getStringTypeAccess().getGroup(), "rule__StringType__Group__0");
					put(grammarAccess.getStringTypeAccess().getGroup_3(), "rule__StringType__Group_3__0");
					put(grammarAccess.getStringTypeAccess().getGroup_4(), "rule__StringType__Group_4__0");
					put(grammarAccess.getStringTypeAccess().getGroup_5(), "rule__StringType__Group_5__0");
					put(grammarAccess.getStringTypeAccess().getGroup_6(), "rule__StringType__Group_6__0");
					put(grammarAccess.getStringTypeAccess().getGroup_7(), "rule__StringType__Group_7__0");
					put(grammarAccess.getEObjectTypeAccess().getGroup(), "rule__EObjectType__Group__0");
					put(grammarAccess.getEObjectTypeAccess().getGroup_3(), "rule__EObjectType__Group_3__0");
					put(grammarAccess.getEObjectTypeAccess().getGroup_4(), "rule__EObjectType__Group_4__0");
					put(grammarAccess.getBooleanTypeAccess().getGroup(), "rule__BooleanType__Group__0");
					put(grammarAccess.getBooleanTypeAccess().getGroup_3(), "rule__BooleanType__Group_3__0");
					put(grammarAccess.getNumericTypeAccess().getGroup(), "rule__NumericType__Group__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_5(), "rule__NumericType__Group_5__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_6(), "rule__NumericType__Group_6__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_7(), "rule__NumericType__Group_7__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_8(), "rule__NumericType__Group_8__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_9(), "rule__NumericType__Group_9__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_10(), "rule__NumericType__Group_10__0");
					put(grammarAccess.getEnumerationTypeAccess().getGroup(), "rule__EnumerationType__Group__0");
					put(grammarAccess.getEnumerationTypeAccess().getGroup_6(), "rule__EnumerationType__Group_6__0");
					put(grammarAccess.getEnumerationTypeAccess().getGroup_8(), "rule__EnumerationType__Group_8__0");
					put(grammarAccess.getEnumerationLiteralAccess().getGroup(), "rule__EnumerationLiteral__Group__0");
					put(grammarAccess.getEnumerationLiteralAccess().getGroup_2(), "rule__EnumerationLiteral__Group_2__0");
					put(grammarAccess.getRecordTypeAccess().getGroup(), "rule__RecordType__Group__0");
					put(grammarAccess.getRecordTypeAccess().getGroup_3(), "rule__RecordType__Group_3__0");
					put(grammarAccess.getRecordTypeAccess().getGroup_7(), "rule__RecordType__Group_7__0");
					put(grammarAccess.getRecordFieldAccess().getGroup(), "rule__RecordField__Group__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_5(), "rule__RecordField__Group_5__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_6(), "rule__RecordField__Group_6__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_7(), "rule__RecordField__Group_7__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_7_1(), "rule__RecordField__Group_7_1__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_8(), "rule__RecordField__Group_8__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_8_3(), "rule__RecordField__Group_8_3__0");
					put(grammarAccess.getArrayTypeAccess().getGroup(), "rule__ArrayType__Group__0");
					put(grammarAccess.getArrayTypeAccess().getGroup_4(), "rule__ArrayType__Group_4__0");
					put(grammarAccess.getEIntegerObjectAccess().getGroup(), "rule__EIntegerObject__Group__0");
					put(grammarAccess.getNameIDAccess().getGroup_0(), "rule__NameID__Group_0__0");
					put(grammarAccess.getExtensionAccess().getNameAssignment_1(), "rule__Extension__NameAssignment_1");
					put(grammarAccess.getExtensionAccess().getSchemeAssignment_3(), "rule__Extension__SchemeAssignment_3");
					put(grammarAccess.getExtensionAccess().getDescriptionAssignment_4_1(), "rule__Extension__DescriptionAssignment_4_1");
					put(grammarAccess.getExtensionAccess().getSpecificationAssignment_5_1(), "rule__Extension__SpecificationAssignment_5_1");
					put(grammarAccess.getExtensionAccess().getImportAssignment_6_1(), "rule__Extension__ImportAssignment_6_1");
					put(grammarAccess.getExtensionAccess().getKindsAssignment_7_0(), "rule__Extension__KindsAssignment_7_0");
					put(grammarAccess.getExtensionAccess().getMixinsAssignment_7_1(), "rule__Extension__MixinsAssignment_7_1");
					put(grammarAccess.getExtensionAccess().getTypesAssignment_7_2(), "rule__Extension__TypesAssignment_7_2");
					put(grammarAccess.getKindAccess().getNameAssignment_1(), "rule__Kind__NameAssignment_1");
					put(grammarAccess.getKindAccess().getParentAssignment_2_1(), "rule__Kind__ParentAssignment_2_1");
					put(grammarAccess.getKindAccess().getSourceAssignment_3_1(), "rule__Kind__SourceAssignment_3_1");
					put(grammarAccess.getKindAccess().getTargetAssignment_4_1(), "rule__Kind__TargetAssignment_4_1");
					put(grammarAccess.getKindAccess().getAnnotationsAssignment_5_2(), "rule__Kind__AnnotationsAssignment_5_2");
					put(grammarAccess.getKindAccess().getAnnotationsAssignment_5_3_1(), "rule__Kind__AnnotationsAssignment_5_3_1");
					put(grammarAccess.getKindAccess().getTitleAssignment_7_1(), "rule__Kind__TitleAssignment_7_1");
					put(grammarAccess.getKindAccess().getSchemeAssignment_9(), "rule__Kind__SchemeAssignment_9");
					put(grammarAccess.getKindAccess().getAttributesAssignment_10_0(), "rule__Kind__AttributesAssignment_10_0");
					put(grammarAccess.getKindAccess().getActionsAssignment_10_1(), "rule__Kind__ActionsAssignment_10_1");
					put(grammarAccess.getKindAccess().getConstraintsAssignment_10_2(), "rule__Kind__ConstraintsAssignment_10_2");
					put(grammarAccess.getKindAccess().getFsmAssignment_11_1(), "rule__Kind__FsmAssignment_11_1");
					put(grammarAccess.getMixinAccess().getNameAssignment_1(), "rule__Mixin__NameAssignment_1");
					put(grammarAccess.getMixinAccess().getDependsAssignment_2_2(), "rule__Mixin__DependsAssignment_2_2");
					put(grammarAccess.getMixinAccess().getDependsAssignment_2_3_1(), "rule__Mixin__DependsAssignment_2_3_1");
					put(grammarAccess.getMixinAccess().getAppliesAssignment_3_2(), "rule__Mixin__AppliesAssignment_3_2");
					put(grammarAccess.getMixinAccess().getAppliesAssignment_3_3_1(), "rule__Mixin__AppliesAssignment_3_3_1");
					put(grammarAccess.getMixinAccess().getAnnotationsAssignment_4_2(), "rule__Mixin__AnnotationsAssignment_4_2");
					put(grammarAccess.getMixinAccess().getAnnotationsAssignment_4_3_1(), "rule__Mixin__AnnotationsAssignment_4_3_1");
					put(grammarAccess.getMixinAccess().getSchemeAssignment_7(), "rule__Mixin__SchemeAssignment_7");
					put(grammarAccess.getMixinAccess().getTitleAssignment_8_1(), "rule__Mixin__TitleAssignment_8_1");
					put(grammarAccess.getMixinAccess().getAttributesAssignment_9_0(), "rule__Mixin__AttributesAssignment_9_0");
					put(grammarAccess.getMixinAccess().getActionsAssignment_9_1(), "rule__Mixin__ActionsAssignment_9_1");
					put(grammarAccess.getMixinAccess().getConstraintsAssignment_9_2(), "rule__Mixin__ConstraintsAssignment_9_2");
					put(grammarAccess.getAnnotationAccess().getKeyAssignment_3(), "rule__Annotation__KeyAssignment_3");
					put(grammarAccess.getAnnotationAccess().getValueAssignment_5(), "rule__Annotation__ValueAssignment_5");
					put(grammarAccess.getAttributeAccess().getMutableAssignment_1(), "rule__Attribute__MutableAssignment_1");
					put(grammarAccess.getAttributeAccess().getRequiredAssignment_2(), "rule__Attribute__RequiredAssignment_2");
					put(grammarAccess.getAttributeAccess().getNameAssignment_3(), "rule__Attribute__NameAssignment_3");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_5_1(), "rule__Attribute__TypeAssignment_5_1");
					put(grammarAccess.getAttributeAccess().getDefaultAssignment_6_1(), "rule__Attribute__DefaultAssignment_6_1");
					put(grammarAccess.getAttributeAccess().getDescriptionAssignment_7_1_1(), "rule__Attribute__DescriptionAssignment_7_1_1");
					put(grammarAccess.getAttributeAccess().getAnnotationsAssignment_8_2(), "rule__Attribute__AnnotationsAssignment_8_2");
					put(grammarAccess.getAttributeAccess().getAnnotationsAssignment_8_3_1(), "rule__Attribute__AnnotationsAssignment_8_3_1");
					put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
					put(grammarAccess.getActionAccess().getSchemeAssignment_3(), "rule__Action__SchemeAssignment_3");
					put(grammarAccess.getActionAccess().getAttributesAssignment_4_1(), "rule__Action__AttributesAssignment_4_1");
					put(grammarAccess.getActionAccess().getAttributesAssignment_4_2_1(), "rule__Action__AttributesAssignment_4_2_1");
					put(grammarAccess.getActionAccess().getTitleAssignment_5_2(), "rule__Action__TitleAssignment_5_2");
					put(grammarAccess.getActionAccess().getAnnotationsAssignment_6_2(), "rule__Action__AnnotationsAssignment_6_2");
					put(grammarAccess.getActionAccess().getAnnotationsAssignment_6_3_1(), "rule__Action__AnnotationsAssignment_6_3_1");
					put(grammarAccess.getParameterDeclAccess().getNameAssignment_0(), "rule__ParameterDecl__NameAssignment_0");
					put(grammarAccess.getParameterDeclAccess().getTypeAssignment_2(), "rule__ParameterDecl__TypeAssignment_2");
					put(grammarAccess.getParameterDeclAccess().getDefaultAssignment_3_1(), "rule__ParameterDecl__DefaultAssignment_3_1");
					put(grammarAccess.getConstraintAccess().getNameAssignment_1(), "rule__Constraint__NameAssignment_1");
					put(grammarAccess.getConstraintAccess().getDescriptionAssignment_2_1(), "rule__Constraint__DescriptionAssignment_2_1");
					put(grammarAccess.getConstraintAccess().getBodyAssignment_4(), "rule__Constraint__BodyAssignment_4");
					put(grammarAccess.getFSMAccess().getAttributeAssignment_3(), "rule__FSM__AttributeAssignment_3");
					put(grammarAccess.getFSMAccess().getOwnedStateAssignment_4_2(), "rule__FSM__OwnedStateAssignment_4_2");
					put(grammarAccess.getFSMAccess().getOwnedStateAssignment_4_3_1(), "rule__FSM__OwnedStateAssignment_4_3_1");
					put(grammarAccess.getStateAccess().getInitialAssignment_2(), "rule__State__InitialAssignment_2");
					put(grammarAccess.getStateAccess().getFinalAssignment_3(), "rule__State__FinalAssignment_3");
					put(grammarAccess.getStateAccess().getLiteralAssignment_4_1(), "rule__State__LiteralAssignment_4_1");
					put(grammarAccess.getStateAccess().getOutgoingTransitionAssignment_5_2(), "rule__State__OutgoingTransitionAssignment_5_2");
					put(grammarAccess.getTransitionAccess().getTargetAssignment_3(), "rule__Transition__TargetAssignment_3");
					put(grammarAccess.getTransitionAccess().getActionAssignment_4_1(), "rule__Transition__ActionAssignment_4_1");
					put(grammarAccess.getStringTypeAccess().getNameAssignment_1(), "rule__StringType__NameAssignment_1");
					put(grammarAccess.getStringTypeAccess().getDocumentationAssignment_3_1(), "rule__StringType__DocumentationAssignment_3_1");
					put(grammarAccess.getStringTypeAccess().getPatternAssignment_4_1(), "rule__StringType__PatternAssignment_4_1");
					put(grammarAccess.getStringTypeAccess().getLengthAssignment_5_1(), "rule__StringType__LengthAssignment_5_1");
					put(grammarAccess.getStringTypeAccess().getMinLengthAssignment_6_1(), "rule__StringType__MinLengthAssignment_6_1");
					put(grammarAccess.getStringTypeAccess().getMaxLengthAssignment_7_1(), "rule__StringType__MaxLengthAssignment_7_1");
					put(grammarAccess.getEObjectTypeAccess().getNameAssignment_1(), "rule__EObjectType__NameAssignment_1");
					put(grammarAccess.getEObjectTypeAccess().getDocumentationAssignment_3_1(), "rule__EObjectType__DocumentationAssignment_3_1");
					put(grammarAccess.getEObjectTypeAccess().getInstanceClassNameAssignment_4_1(), "rule__EObjectType__InstanceClassNameAssignment_4_1");
					put(grammarAccess.getBooleanTypeAccess().getNameAssignment_1(), "rule__BooleanType__NameAssignment_1");
					put(grammarAccess.getBooleanTypeAccess().getDocumentationAssignment_3_1(), "rule__BooleanType__DocumentationAssignment_3_1");
					put(grammarAccess.getNumericTypeAccess().getNameAssignment_1(), "rule__NumericType__NameAssignment_1");
					put(grammarAccess.getNumericTypeAccess().getTypeAssignment_3(), "rule__NumericType__TypeAssignment_3");
					put(grammarAccess.getNumericTypeAccess().getDocumentationAssignment_5_1(), "rule__NumericType__DocumentationAssignment_5_1");
					put(grammarAccess.getNumericTypeAccess().getTotalDigitsAssignment_6_1(), "rule__NumericType__TotalDigitsAssignment_6_1");
					put(grammarAccess.getNumericTypeAccess().getMinExclusiveAssignment_7_1(), "rule__NumericType__MinExclusiveAssignment_7_1");
					put(grammarAccess.getNumericTypeAccess().getMaxExclusiveAssignment_8_1(), "rule__NumericType__MaxExclusiveAssignment_8_1");
					put(grammarAccess.getNumericTypeAccess().getMinInclusiveAssignment_9_1(), "rule__NumericType__MinInclusiveAssignment_9_1");
					put(grammarAccess.getNumericTypeAccess().getMaxInclusiveAssignment_10_1(), "rule__NumericType__MaxInclusiveAssignment_10_1");
					put(grammarAccess.getEnumerationTypeAccess().getNameAssignment_1(), "rule__EnumerationType__NameAssignment_1");
					put(grammarAccess.getEnumerationTypeAccess().getLiteralsAssignment_5(), "rule__EnumerationType__LiteralsAssignment_5");
					put(grammarAccess.getEnumerationTypeAccess().getLiteralsAssignment_6_1(), "rule__EnumerationType__LiteralsAssignment_6_1");
					put(grammarAccess.getEnumerationTypeAccess().getDocumentationAssignment_8_1(), "rule__EnumerationType__DocumentationAssignment_8_1");
					put(grammarAccess.getEnumerationLiteralAccess().getNameAssignment_0(), "rule__EnumerationLiteral__NameAssignment_0");
					put(grammarAccess.getEnumerationLiteralAccess().getDocumentationAssignment_2_1(), "rule__EnumerationLiteral__DocumentationAssignment_2_1");
					put(grammarAccess.getRecordTypeAccess().getNameAssignment_1(), "rule__RecordType__NameAssignment_1");
					put(grammarAccess.getRecordTypeAccess().getDocumentationAssignment_3_1(), "rule__RecordType__DocumentationAssignment_3_1");
					put(grammarAccess.getRecordTypeAccess().getRecordFieldsAssignment_6(), "rule__RecordType__RecordFieldsAssignment_6");
					put(grammarAccess.getRecordTypeAccess().getRecordFieldsAssignment_7_1(), "rule__RecordType__RecordFieldsAssignment_7_1");
					put(grammarAccess.getRecordFieldAccess().getMutableAssignment_1(), "rule__RecordField__MutableAssignment_1");
					put(grammarAccess.getRecordFieldAccess().getRequiredAssignment_2(), "rule__RecordField__RequiredAssignment_2");
					put(grammarAccess.getRecordFieldAccess().getNameAssignment_3(), "rule__RecordField__NameAssignment_3");
					put(grammarAccess.getRecordFieldAccess().getTypeAssignment_5_1(), "rule__RecordField__TypeAssignment_5_1");
					put(grammarAccess.getRecordFieldAccess().getDefaultAssignment_6_1(), "rule__RecordField__DefaultAssignment_6_1");
					put(grammarAccess.getRecordFieldAccess().getDescriptionAssignment_7_1_1(), "rule__RecordField__DescriptionAssignment_7_1_1");
					put(grammarAccess.getRecordFieldAccess().getAnnotationsAssignment_8_2(), "rule__RecordField__AnnotationsAssignment_8_2");
					put(grammarAccess.getRecordFieldAccess().getAnnotationsAssignment_8_3_1(), "rule__RecordField__AnnotationsAssignment_8_3_1");
					put(grammarAccess.getArrayTypeAccess().getNameAssignment_1(), "rule__ArrayType__NameAssignment_1");
					put(grammarAccess.getArrayTypeAccess().getTypeAssignment_3(), "rule__ArrayType__TypeAssignment_3");
					put(grammarAccess.getArrayTypeAccess().getDocumentationAssignment_4_2(), "rule__ArrayType__DocumentationAssignment_4_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public OCCIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OCCIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
