/*
 * generated by Xtext 2.12.0
 */
package org.eclipse.cmf.occi.core.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.cmf.occi.core.xtext.ide.contentassist.antlr.internal.InternalOCCIParser;
import org.eclipse.cmf.occi.core.xtext.services.OCCIGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class OCCIParser extends AbstractContentAssistParser {

	@Inject
	private OCCIGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalOCCIParser createParser() {
		InternalOCCIParser result = new InternalOCCIParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGrammarAccess().getAlternatives(), "rule__Grammar__Alternatives");
					put(grammarAccess.getExtensionAccess().getAlternatives_7(), "rule__Extension__Alternatives_7");
					put(grammarAccess.getKindAccess().getAlternatives_6_1(), "rule__Kind__Alternatives_6_1");
					put(grammarAccess.getMixinAccess().getAlternatives_7_1(), "rule__Mixin__Alternatives_7_1");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getTypeIDAccess().getAlternatives(), "rule__TypeID__Alternatives");
					put(grammarAccess.getQualifiedIDAccess().getAlternatives(), "rule__QualifiedID__Alternatives");
					put(grammarAccess.getNameIDAccess().getAlternatives(), "rule__NameID__Alternatives");
					put(grammarAccess.getNameIDAccess().getAlternatives_0_1(), "rule__NameID__Alternatives_0_1");
					put(grammarAccess.getKEYWORDAccess().getAlternatives(), "rule__KEYWORD__Alternatives");
					put(grammarAccess.getNumericTypeEnumAccess().getAlternatives(), "rule__NumericTypeEnum__Alternatives");
					put(grammarAccess.getConfigurationAccess().getGroup(), "rule__Configuration__Group__0");
					put(grammarAccess.getConfigurationAccess().getGroup_2(), "rule__Configuration__Group_2__0");
					put(grammarAccess.getConfigurationAccess().getGroup_3(), "rule__Configuration__Group_3__0");
					put(grammarAccess.getConfigurationAccess().getGroup_4(), "rule__Configuration__Group_4__0");
					put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
					put(grammarAccess.getResourceAccess().getGroup_4(), "rule__Resource__Group_4__0");
					put(grammarAccess.getResourceAccess().getGroup_5(), "rule__Resource__Group_5__0");
					put(grammarAccess.getResourceAccess().getGroup_6(), "rule__Resource__Group_6__0");
					put(grammarAccess.getResourceAccess().getGroup_7(), "rule__Resource__Group_7__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getLinkAccess().getGroup_4(), "rule__Link__Group_4__0");
					put(grammarAccess.getLinkAccess().getGroup_5(), "rule__Link__Group_5__0");
					put(grammarAccess.getLinkAccess().getGroup_8(), "rule__Link__Group_8__0");
					put(grammarAccess.getMixinBaseAccess().getGroup(), "rule__MixinBase__Group__0");
					put(grammarAccess.getAttributeStateAccess().getGroup(), "rule__AttributeState__Group__0");
					put(grammarAccess.getExtensionAccess().getGroup(), "rule__Extension__Group__0");
					put(grammarAccess.getExtensionAccess().getGroup_4(), "rule__Extension__Group_4__0");
					put(grammarAccess.getExtensionAccess().getGroup_5(), "rule__Extension__Group_5__0");
					put(grammarAccess.getExtensionAccess().getGroup_6(), "rule__Extension__Group_6__0");
					put(grammarAccess.getExtensionAccess().getGroup_6_2(), "rule__Extension__Group_6_2__0");
					put(grammarAccess.getKindAccess().getGroup(), "rule__Kind__Group__0");
					put(grammarAccess.getKindAccess().getGroup_2(), "rule__Kind__Group_2__0");
					put(grammarAccess.getKindAccess().getGroup_3(), "rule__Kind__Group_3__0");
					put(grammarAccess.getKindAccess().getGroup_3_2(), "rule__Kind__Group_3_2__0");
					put(grammarAccess.getKindAccess().getGroup_4(), "rule__Kind__Group_4__0");
					put(grammarAccess.getKindAccess().getGroup_4_2(), "rule__Kind__Group_4_2__0");
					put(grammarAccess.getKindAccess().getGroup_5(), "rule__Kind__Group_5__0");
					put(grammarAccess.getKindAccess().getGroup_6(), "rule__Kind__Group_6__0");
					put(grammarAccess.getKindAccess().getGroup_8(), "rule__Kind__Group_8__0");
					put(grammarAccess.getKindAccess().getGroup_8_3(), "rule__Kind__Group_8_3__0");
					put(grammarAccess.getMixinAccess().getGroup(), "rule__Mixin__Group__0");
					put(grammarAccess.getMixinAccess().getGroup_2(), "rule__Mixin__Group_2__0");
					put(grammarAccess.getMixinAccess().getGroup_2_3(), "rule__Mixin__Group_2_3__0");
					put(grammarAccess.getMixinAccess().getGroup_3(), "rule__Mixin__Group_3__0");
					put(grammarAccess.getMixinAccess().getGroup_3_3(), "rule__Mixin__Group_3_3__0");
					put(grammarAccess.getMixinAccess().getGroup_4(), "rule__Mixin__Group_4__0");
					put(grammarAccess.getMixinAccess().getGroup_7(), "rule__Mixin__Group_7__0");
					put(grammarAccess.getMixinAccess().getGroup_9(), "rule__Mixin__Group_9__0");
					put(grammarAccess.getMixinAccess().getGroup_9_3(), "rule__Mixin__Group_9_3__0");
					put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_4(), "rule__Attribute__Group_4__0");
					put(grammarAccess.getAttributeAccess().getGroup_5(), "rule__Attribute__Group_5__0");
					put(grammarAccess.getAttributeAccess().getGroup_6(), "rule__Attribute__Group_6__0");
					put(grammarAccess.getAttributeAccess().getGroup_7(), "rule__Attribute__Group_7__0");
					put(grammarAccess.getAttributeAccess().getGroup_7_3(), "rule__Attribute__Group_7_3__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionAccess().getGroup_2(), "rule__Action__Group_2__0");
					put(grammarAccess.getActionAccess().getGroup_2_2(), "rule__Action__Group_2_2__0");
					put(grammarAccess.getActionAccess().getGroup_3(), "rule__Action__Group_3__0");
					put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
					put(grammarAccess.getActionAccess().getGroup_4_3(), "rule__Action__Group_4_3__0");
					put(grammarAccess.getParameterDeclAccess().getGroup(), "rule__ParameterDecl__Group__0");
					put(grammarAccess.getParameterDeclAccess().getGroup_3(), "rule__ParameterDecl__Group_3__0");
					put(grammarAccess.getConstraintAccess().getGroup(), "rule__Constraint__Group__0");
					put(grammarAccess.getConstraintAccess().getGroup_2(), "rule__Constraint__Group_2__0");
					put(grammarAccess.getFSMAccess().getGroup(), "rule__FSM__Group__0");
					put(grammarAccess.getFSMAccess().getGroup_3(), "rule__FSM__Group_3__0");
					put(grammarAccess.getFSMAccess().getGroup_3_2(), "rule__FSM__Group_3_2__0");
					put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
					put(grammarAccess.getStateAccess().getGroup_4(), "rule__State__Group_4__0");
					put(grammarAccess.getStateAccess().getGroup_4_3(), "rule__State__Group_4_3__0");
					put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup_0(), "rule__Transition__Group_0__0");
					put(grammarAccess.getStringTypeAccess().getGroup(), "rule__StringType__Group__0");
					put(grammarAccess.getStringTypeAccess().getGroup_2(), "rule__StringType__Group_2__0");
					put(grammarAccess.getStringTypeAccess().getGroup_3(), "rule__StringType__Group_3__0");
					put(grammarAccess.getStringTypeAccess().getGroup_4(), "rule__StringType__Group_4__0");
					put(grammarAccess.getStringTypeAccess().getGroup_5(), "rule__StringType__Group_5__0");
					put(grammarAccess.getStringTypeAccess().getGroup_6(), "rule__StringType__Group_6__0");
					put(grammarAccess.getEObjectTypeAccess().getGroup(), "rule__EObjectType__Group__0");
					put(grammarAccess.getEObjectTypeAccess().getGroup_2(), "rule__EObjectType__Group_2__0");
					put(grammarAccess.getEObjectTypeAccess().getGroup_3(), "rule__EObjectType__Group_3__0");
					put(grammarAccess.getBooleanTypeAccess().getGroup(), "rule__BooleanType__Group__0");
					put(grammarAccess.getBooleanTypeAccess().getGroup_2(), "rule__BooleanType__Group_2__0");
					put(grammarAccess.getNumericTypeAccess().getGroup(), "rule__NumericType__Group__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_4(), "rule__NumericType__Group_4__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_5(), "rule__NumericType__Group_5__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_6(), "rule__NumericType__Group_6__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_7(), "rule__NumericType__Group_7__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_8(), "rule__NumericType__Group_8__0");
					put(grammarAccess.getNumericTypeAccess().getGroup_9(), "rule__NumericType__Group_9__0");
					put(grammarAccess.getEnumerationTypeAccess().getGroup(), "rule__EnumerationType__Group__0");
					put(grammarAccess.getEnumerationTypeAccess().getGroup_2(), "rule__EnumerationType__Group_2__0");
					put(grammarAccess.getEnumerationTypeAccess().getGroup_6(), "rule__EnumerationType__Group_6__0");
					put(grammarAccess.getEnumerationLiteralAccess().getGroup(), "rule__EnumerationLiteral__Group__0");
					put(grammarAccess.getEnumerationLiteralAccess().getGroup_1(), "rule__EnumerationLiteral__Group_1__0");
					put(grammarAccess.getRecordTypeAccess().getGroup(), "rule__RecordType__Group__0");
					put(grammarAccess.getRecordTypeAccess().getGroup_2(), "rule__RecordType__Group_2__0");
					put(grammarAccess.getRecordTypeAccess().getGroup_5(), "rule__RecordType__Group_5__0");
					put(grammarAccess.getRecordFieldAccess().getGroup(), "rule__RecordField__Group__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_3(), "rule__RecordField__Group_3__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_4(), "rule__RecordField__Group_4__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_5(), "rule__RecordField__Group_5__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_6(), "rule__RecordField__Group_6__0");
					put(grammarAccess.getRecordFieldAccess().getGroup_6_3(), "rule__RecordField__Group_6_3__0");
					put(grammarAccess.getArrayTypeAccess().getGroup(), "rule__ArrayType__Group__0");
					put(grammarAccess.getArrayTypeAccess().getGroup_4(), "rule__ArrayType__Group_4__0");
					put(grammarAccess.getEIntegerObjectAccess().getGroup(), "rule__EIntegerObject__Group__0");
					put(grammarAccess.getNameIDAccess().getGroup_0(), "rule__NameID__Group_0__0");
					put(grammarAccess.getConfigurationAccess().getDescriptionAssignment_2_1(), "rule__Configuration__DescriptionAssignment_2_1");
					put(grammarAccess.getConfigurationAccess().getLocationAssignment_3_1(), "rule__Configuration__LocationAssignment_3_1");
					put(grammarAccess.getConfigurationAccess().getUseAssignment_4_1(), "rule__Configuration__UseAssignment_4_1");
					put(grammarAccess.getConfigurationAccess().getResourcesAssignment_5(), "rule__Configuration__ResourcesAssignment_5");
					put(grammarAccess.getConfigurationAccess().getMixinsAssignment_6(), "rule__Configuration__MixinsAssignment_6");
					put(grammarAccess.getResourceAccess().getIdAssignment_1(), "rule__Resource__IdAssignment_1");
					put(grammarAccess.getResourceAccess().getKindAssignment_3(), "rule__Resource__KindAssignment_3");
					put(grammarAccess.getResourceAccess().getTitleAssignment_4_1(), "rule__Resource__TitleAssignment_4_1");
					put(grammarAccess.getResourceAccess().getLocationAssignment_5_1(), "rule__Resource__LocationAssignment_5_1");
					put(grammarAccess.getResourceAccess().getSummaryAssignment_6_1(), "rule__Resource__SummaryAssignment_6_1");
					put(grammarAccess.getResourceAccess().getPartsAssignment_7_1(), "rule__Resource__PartsAssignment_7_1");
					put(grammarAccess.getResourceAccess().getAttributesAssignment_7_2(), "rule__Resource__AttributesAssignment_7_2");
					put(grammarAccess.getResourceAccess().getLinksAssignment_7_3(), "rule__Resource__LinksAssignment_7_3");
					put(grammarAccess.getLinkAccess().getIdAssignment_1(), "rule__Link__IdAssignment_1");
					put(grammarAccess.getLinkAccess().getKindAssignment_3(), "rule__Link__KindAssignment_3");
					put(grammarAccess.getLinkAccess().getTitleAssignment_4_1(), "rule__Link__TitleAssignment_4_1");
					put(grammarAccess.getLinkAccess().getLocationAssignment_5_1(), "rule__Link__LocationAssignment_5_1");
					put(grammarAccess.getLinkAccess().getTargetAssignment_7(), "rule__Link__TargetAssignment_7");
					put(grammarAccess.getLinkAccess().getAttributesAssignment_8_1(), "rule__Link__AttributesAssignment_8_1");
					put(grammarAccess.getLinkAccess().getPartsAssignment_8_2(), "rule__Link__PartsAssignment_8_2");
					put(grammarAccess.getMixinBaseAccess().getMixinAssignment_1(), "rule__MixinBase__MixinAssignment_1");
					put(grammarAccess.getMixinBaseAccess().getAttributesAssignment_3(), "rule__MixinBase__AttributesAssignment_3");
					put(grammarAccess.getAttributeStateAccess().getNameAssignment_1(), "rule__AttributeState__NameAssignment_1");
					put(grammarAccess.getAttributeStateAccess().getValueAssignment_3(), "rule__AttributeState__ValueAssignment_3");
					put(grammarAccess.getExtensionAccess().getNameAssignment_1(), "rule__Extension__NameAssignment_1");
					put(grammarAccess.getExtensionAccess().getSchemeAssignment_3(), "rule__Extension__SchemeAssignment_3");
					put(grammarAccess.getExtensionAccess().getDescriptionAssignment_4_1(), "rule__Extension__DescriptionAssignment_4_1");
					put(grammarAccess.getExtensionAccess().getSpecificationAssignment_5_1(), "rule__Extension__SpecificationAssignment_5_1");
					put(grammarAccess.getExtensionAccess().getImportAssignment_6_1(), "rule__Extension__ImportAssignment_6_1");
					put(grammarAccess.getExtensionAccess().getKindsAssignment_7_0(), "rule__Extension__KindsAssignment_7_0");
					put(grammarAccess.getExtensionAccess().getMixinsAssignment_7_1(), "rule__Extension__MixinsAssignment_7_1");
					put(grammarAccess.getExtensionAccess().getTypesAssignment_7_2(), "rule__Extension__TypesAssignment_7_2");
					put(grammarAccess.getKindAccess().getNameAssignment_1(), "rule__Kind__NameAssignment_1");
					put(grammarAccess.getKindAccess().getParentAssignment_2_1(), "rule__Kind__ParentAssignment_2_1");
					put(grammarAccess.getKindAccess().getSourceAssignment_3_1(), "rule__Kind__SourceAssignment_3_1");
					put(grammarAccess.getKindAccess().getSourceAssignment_3_2_1(), "rule__Kind__SourceAssignment_3_2_1");
					put(grammarAccess.getKindAccess().getTargetAssignment_4_1(), "rule__Kind__TargetAssignment_4_1");
					put(grammarAccess.getKindAccess().getTargetAssignment_4_2_1(), "rule__Kind__TargetAssignment_4_2_1");
					put(grammarAccess.getKindAccess().getTitleAssignment_5_1(), "rule__Kind__TitleAssignment_5_1");
					put(grammarAccess.getKindAccess().getAttributesAssignment_6_1_0(), "rule__Kind__AttributesAssignment_6_1_0");
					put(grammarAccess.getKindAccess().getActionsAssignment_6_1_1(), "rule__Kind__ActionsAssignment_6_1_1");
					put(grammarAccess.getKindAccess().getConstraintsAssignment_6_1_2(), "rule__Kind__ConstraintsAssignment_6_1_2");
					put(grammarAccess.getKindAccess().getFsmAssignment_7(), "rule__Kind__FsmAssignment_7");
					put(grammarAccess.getKindAccess().getAnnotationsAssignment_8_2(), "rule__Kind__AnnotationsAssignment_8_2");
					put(grammarAccess.getKindAccess().getAnnotationsAssignment_8_3_1(), "rule__Kind__AnnotationsAssignment_8_3_1");
					put(grammarAccess.getMixinAccess().getNameAssignment_1(), "rule__Mixin__NameAssignment_1");
					put(grammarAccess.getMixinAccess().getDependsAssignment_2_2(), "rule__Mixin__DependsAssignment_2_2");
					put(grammarAccess.getMixinAccess().getDependsAssignment_2_3_1(), "rule__Mixin__DependsAssignment_2_3_1");
					put(grammarAccess.getMixinAccess().getAppliesAssignment_3_2(), "rule__Mixin__AppliesAssignment_3_2");
					put(grammarAccess.getMixinAccess().getAppliesAssignment_3_3_1(), "rule__Mixin__AppliesAssignment_3_3_1");
					put(grammarAccess.getMixinAccess().getTitleAssignment_4_1(), "rule__Mixin__TitleAssignment_4_1");
					put(grammarAccess.getMixinAccess().getSchemeAssignment_6(), "rule__Mixin__SchemeAssignment_6");
					put(grammarAccess.getMixinAccess().getAttributesAssignment_7_1_0(), "rule__Mixin__AttributesAssignment_7_1_0");
					put(grammarAccess.getMixinAccess().getActionsAssignment_7_1_1(), "rule__Mixin__ActionsAssignment_7_1_1");
					put(grammarAccess.getMixinAccess().getConstraintsAssignment_7_1_2(), "rule__Mixin__ConstraintsAssignment_7_1_2");
					put(grammarAccess.getMixinAccess().getFsmAssignment_8(), "rule__Mixin__FsmAssignment_8");
					put(grammarAccess.getMixinAccess().getAnnotationsAssignment_9_2(), "rule__Mixin__AnnotationsAssignment_9_2");
					put(grammarAccess.getMixinAccess().getAnnotationsAssignment_9_3_1(), "rule__Mixin__AnnotationsAssignment_9_3_1");
					put(grammarAccess.getAnnotationAccess().getKeyAssignment_2(), "rule__Annotation__KeyAssignment_2");
					put(grammarAccess.getAnnotationAccess().getValueAssignment_4(), "rule__Annotation__ValueAssignment_4");
					put(grammarAccess.getAttributeAccess().getMutableAssignment_1(), "rule__Attribute__MutableAssignment_1");
					put(grammarAccess.getAttributeAccess().getRequiredAssignment_2(), "rule__Attribute__RequiredAssignment_2");
					put(grammarAccess.getAttributeAccess().getNameAssignment_3(), "rule__Attribute__NameAssignment_3");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_4_1(), "rule__Attribute__TypeAssignment_4_1");
					put(grammarAccess.getAttributeAccess().getDefaultAssignment_5_1(), "rule__Attribute__DefaultAssignment_5_1");
					put(grammarAccess.getAttributeAccess().getDescriptionAssignment_6_1(), "rule__Attribute__DescriptionAssignment_6_1");
					put(grammarAccess.getAttributeAccess().getAnnotationsAssignment_7_2(), "rule__Attribute__AnnotationsAssignment_7_2");
					put(grammarAccess.getAttributeAccess().getAnnotationsAssignment_7_3_1(), "rule__Attribute__AnnotationsAssignment_7_3_1");
					put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
					put(grammarAccess.getActionAccess().getAttributesAssignment_2_1(), "rule__Action__AttributesAssignment_2_1");
					put(grammarAccess.getActionAccess().getAttributesAssignment_2_2_1(), "rule__Action__AttributesAssignment_2_2_1");
					put(grammarAccess.getActionAccess().getTitleAssignment_3_1(), "rule__Action__TitleAssignment_3_1");
					put(grammarAccess.getActionAccess().getAnnotationsAssignment_4_2(), "rule__Action__AnnotationsAssignment_4_2");
					put(grammarAccess.getActionAccess().getAnnotationsAssignment_4_3_1(), "rule__Action__AnnotationsAssignment_4_3_1");
					put(grammarAccess.getParameterDeclAccess().getNameAssignment_0(), "rule__ParameterDecl__NameAssignment_0");
					put(grammarAccess.getParameterDeclAccess().getTypeAssignment_2(), "rule__ParameterDecl__TypeAssignment_2");
					put(grammarAccess.getParameterDeclAccess().getDefaultAssignment_3_1(), "rule__ParameterDecl__DefaultAssignment_3_1");
					put(grammarAccess.getConstraintAccess().getNameAssignment_1(), "rule__Constraint__NameAssignment_1");
					put(grammarAccess.getConstraintAccess().getDescriptionAssignment_2_1(), "rule__Constraint__DescriptionAssignment_2_1");
					put(grammarAccess.getConstraintAccess().getBodyAssignment_4(), "rule__Constraint__BodyAssignment_4");
					put(grammarAccess.getFSMAccess().getAttributeAssignment_2(), "rule__FSM__AttributeAssignment_2");
					put(grammarAccess.getFSMAccess().getOwnedStateAssignment_3_1(), "rule__FSM__OwnedStateAssignment_3_1");
					put(grammarAccess.getFSMAccess().getOwnedStateAssignment_3_2_1(), "rule__FSM__OwnedStateAssignment_3_2_1");
					put(grammarAccess.getStateAccess().getInitialAssignment_1(), "rule__State__InitialAssignment_1");
					put(grammarAccess.getStateAccess().getFinalAssignment_2(), "rule__State__FinalAssignment_2");
					put(grammarAccess.getStateAccess().getLiteralAssignment_3(), "rule__State__LiteralAssignment_3");
					put(grammarAccess.getStateAccess().getOutgoingTransitionAssignment_4_2(), "rule__State__OutgoingTransitionAssignment_4_2");
					put(grammarAccess.getStateAccess().getOutgoingTransitionAssignment_4_3_1(), "rule__State__OutgoingTransitionAssignment_4_3_1");
					put(grammarAccess.getTransitionAccess().getActionAssignment_0_1(), "rule__Transition__ActionAssignment_0_1");
					put(grammarAccess.getTransitionAccess().getTargetAssignment_2(), "rule__Transition__TargetAssignment_2");
					put(grammarAccess.getStringTypeAccess().getNameAssignment_1(), "rule__StringType__NameAssignment_1");
					put(grammarAccess.getStringTypeAccess().getDocumentationAssignment_2_1(), "rule__StringType__DocumentationAssignment_2_1");
					put(grammarAccess.getStringTypeAccess().getPatternAssignment_3_1(), "rule__StringType__PatternAssignment_3_1");
					put(grammarAccess.getStringTypeAccess().getLengthAssignment_4_1(), "rule__StringType__LengthAssignment_4_1");
					put(grammarAccess.getStringTypeAccess().getMinLengthAssignment_5_1(), "rule__StringType__MinLengthAssignment_5_1");
					put(grammarAccess.getStringTypeAccess().getMaxLengthAssignment_6_1(), "rule__StringType__MaxLengthAssignment_6_1");
					put(grammarAccess.getEObjectTypeAccess().getNameAssignment_1(), "rule__EObjectType__NameAssignment_1");
					put(grammarAccess.getEObjectTypeAccess().getDocumentationAssignment_2_1(), "rule__EObjectType__DocumentationAssignment_2_1");
					put(grammarAccess.getEObjectTypeAccess().getInstanceClassNameAssignment_3_1(), "rule__EObjectType__InstanceClassNameAssignment_3_1");
					put(grammarAccess.getBooleanTypeAccess().getNameAssignment_1(), "rule__BooleanType__NameAssignment_1");
					put(grammarAccess.getBooleanTypeAccess().getDocumentationAssignment_2_1(), "rule__BooleanType__DocumentationAssignment_2_1");
					put(grammarAccess.getNumericTypeAccess().getNameAssignment_1(), "rule__NumericType__NameAssignment_1");
					put(grammarAccess.getNumericTypeAccess().getTypeAssignment_3(), "rule__NumericType__TypeAssignment_3");
					put(grammarAccess.getNumericTypeAccess().getDocumentationAssignment_4_1(), "rule__NumericType__DocumentationAssignment_4_1");
					put(grammarAccess.getNumericTypeAccess().getTotalDigitsAssignment_5_1(), "rule__NumericType__TotalDigitsAssignment_5_1");
					put(grammarAccess.getNumericTypeAccess().getMinExclusiveAssignment_6_1(), "rule__NumericType__MinExclusiveAssignment_6_1");
					put(grammarAccess.getNumericTypeAccess().getMaxExclusiveAssignment_7_1(), "rule__NumericType__MaxExclusiveAssignment_7_1");
					put(grammarAccess.getNumericTypeAccess().getMinInclusiveAssignment_8_1(), "rule__NumericType__MinInclusiveAssignment_8_1");
					put(grammarAccess.getNumericTypeAccess().getMaxInclusiveAssignment_9_1(), "rule__NumericType__MaxInclusiveAssignment_9_1");
					put(grammarAccess.getEnumerationTypeAccess().getNameAssignment_1(), "rule__EnumerationType__NameAssignment_1");
					put(grammarAccess.getEnumerationTypeAccess().getDocumentationAssignment_2_1(), "rule__EnumerationType__DocumentationAssignment_2_1");
					put(grammarAccess.getEnumerationTypeAccess().getLiteralsAssignment_5(), "rule__EnumerationType__LiteralsAssignment_5");
					put(grammarAccess.getEnumerationTypeAccess().getLiteralsAssignment_6_1(), "rule__EnumerationType__LiteralsAssignment_6_1");
					put(grammarAccess.getEnumerationLiteralAccess().getNameAssignment_0(), "rule__EnumerationLiteral__NameAssignment_0");
					put(grammarAccess.getEnumerationLiteralAccess().getDocumentationAssignment_1_1(), "rule__EnumerationLiteral__DocumentationAssignment_1_1");
					put(grammarAccess.getRecordTypeAccess().getNameAssignment_1(), "rule__RecordType__NameAssignment_1");
					put(grammarAccess.getRecordTypeAccess().getDocumentationAssignment_2_1(), "rule__RecordType__DocumentationAssignment_2_1");
					put(grammarAccess.getRecordTypeAccess().getRecordFieldsAssignment_4(), "rule__RecordType__RecordFieldsAssignment_4");
					put(grammarAccess.getRecordTypeAccess().getRecordFieldsAssignment_5_1(), "rule__RecordType__RecordFieldsAssignment_5_1");
					put(grammarAccess.getRecordFieldAccess().getMutableAssignment_0(), "rule__RecordField__MutableAssignment_0");
					put(grammarAccess.getRecordFieldAccess().getRequiredAssignment_1(), "rule__RecordField__RequiredAssignment_1");
					put(grammarAccess.getRecordFieldAccess().getNameAssignment_2(), "rule__RecordField__NameAssignment_2");
					put(grammarAccess.getRecordFieldAccess().getTypeAssignment_3_1(), "rule__RecordField__TypeAssignment_3_1");
					put(grammarAccess.getRecordFieldAccess().getDefaultAssignment_4_1(), "rule__RecordField__DefaultAssignment_4_1");
					put(grammarAccess.getRecordFieldAccess().getDescriptionAssignment_5_1(), "rule__RecordField__DescriptionAssignment_5_1");
					put(grammarAccess.getRecordFieldAccess().getAnnotationsAssignment_6_2(), "rule__RecordField__AnnotationsAssignment_6_2");
					put(grammarAccess.getRecordFieldAccess().getAnnotationsAssignment_6_3_1(), "rule__RecordField__AnnotationsAssignment_6_3_1");
					put(grammarAccess.getArrayTypeAccess().getNameAssignment_1(), "rule__ArrayType__NameAssignment_1");
					put(grammarAccess.getArrayTypeAccess().getTypeAssignment_3(), "rule__ArrayType__TypeAssignment_3");
					put(grammarAccess.getArrayTypeAccess().getDocumentationAssignment_4_1(), "rule__ArrayType__DocumentationAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public OCCIGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(OCCIGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
